[theme]
primaryColor = "#1e3a8a"
backgroundColor = "#ffffff"  
secondaryBackgroundColor = "#f1f5f9"
textColor = "#1e293b"
font = "sans serif"

[server]
headless = true
port = 8501
enableCORS = false
enableWebsocketCompression = false

[browser]
gatherUsageStats = false
showErrorDetails = false
